name = "gweb3"
version = "0.1.0"

description = "gweb3 is a comprehensible Web3 library for interacting with EVM-based blockchains using Gleam"
licences = ["MIT"]
repository = { type = "github", user = "vidalpaul", repo = "https://github.com/vidalpaul/gweb3" }
links = [{ title = "GitHub repo", href = "https://github.com/vidalpaul/gweb3" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
